### ISSUE TITLE
Control WW(WarmWhite) interface

### ISSUE THREAD

**Issue by Animeimp** [sidoh/ledenet_api#1]
The RGB section is working perfectly, do you still plan on adding the WW control section?  To turn on the WarmWhite is string.char(113) string.char(35) string.char (148) and to turn off is string.char(113) string.char(35) string.char(149)
# Turn off 0x71, 0x24, 0x95
# Turn on 0x71, 0x23, 0x94

**Comment by sidoh** [comment]
No plans to myself, mainly because I don't have a WW strip to test with.

If you want to open up a PR, I'd be happy to take a look.

**Comment by Animeimp** [comment]
I'll have to read up on how to do a pull request.  I have the documentation from the Chinese authors, which I will attach here as well.  One way to test though is move one of your color connections to the W input, and it will come on at a full 255 when you turn the WW on/off.
[4.WIFI RGBW bulb communication protocol.xls.zip](https://github.com/sidoh/ledenet_api/files/67363/4.WIFI.RGBW.bulb.communication.protocol.xls.zip)

**Comment by Animeimp** [comment]
Sorry, that was the Chinese version - here is the english version.
[3.WIFI CCT bulb communication protocol.xls.zip](https://github.com/sidoh/ledenet_api/files/67369/3.WIFI.CCT.bulb.communication.protocol.xls.zip)

**Comment by adamkempenich** [comment]
@Animeimp @sidoh I've gotten the WW working properly (and added support for the physical lightbulbs, as well as the Flux-branded LED bulbs, along with improving the code for @sidoh's other SmartThings integration project.). I can issue a PR (on both projects) and send a copy of the code, if you'd like.

**Comment by sidoh** [comment]
Happy to look at a PR.

**Comment by adamkempenich** [comment]
Thanks, @sidoh. I'll issue a PR in a few days after I get my code cleaned up and more readable.

**Comment by AMVS2** [comment]
@Animeimp I'm trying to discover the protocol for my WiFi370 RGB controller, v3. The protocols are very similar to the link you posted above of the Chinese authors documentation (4. WIFI RGBW ....). Where were you able to find that file of documentation? Can you link me to that? Or, do they have an RGB protocol in english? Thank you!

**Comment by adamkempenich** [comment]
@AMVS2 I'd like to add support for the WiFi370 (and the downlight model), but I won't be able to get to it for a couple of weeks since I'm moving, currently. 
If you're interested, the device type is carried in byte 2 when a discovery request is sent—[The documentation posted above](https://github.com/sidoh/ledenet_api/files/67369/3.WIFI.CCT.bulb.communication.protocol.xls.zip) refers to it as the "Device Name". I have yet to find documentation for the RGB-only device (so far), but if you find any and would be willing to share, it would help a ton!

**Comment by Animeimp** [comment]
That documentation came from the seller.  The miLights are similar, but I'm not sure if they use the checksum or not.

**Comment by Animeimp** [comment]
Also, there is some of the API here - https://www.npmjs.com/package/rgb-led

**Comment by sidoh** [comment]
@Animeimp: For the sake of clarity, what links the documentation you're providing to the particular controller this project is designed to control? It certainly seems like there's some (maybe complete) overlap, but I'm not seeing a reference to this controller in either of these links. I'm curious to see the page you found the spreadsheet on if you have it handy.

**Comment by sidoh** [comment]
Added support for this in the v1.0 release.

**Comment by mattjanssen** [comment]
@Animeimp Do you think the Magic UFO can run all four channels (R + G + B + WW) all the same time?

`api.update_color_data(red: 32, green: 64, blue: 128, warm_white: 192)`

The fact that it's rated at 96W makes me think so. 2 amps \* 4 channels \* 12 volts = 96 watts.

**Comment by sidoh** [comment]
Yes, that should work.

**Comment by aap82** [comment]
@mattjanssen  I can confirm it does,  but I recommend using an amplifier.
